version: "3"

services:

  agora_vnf_manager_database:
    build:
      context: ../dev/database
    container_name: agora-vnf-manager-database
    ports:
      - "5432:5432"
    networks:
      - agora_vnf_manager_network

  agora_vnf_manager_pgadmin:
    image: dpage/pgadmin4
    container_name: agora-vnf-manager-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ../dev/database/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - agora_vnf_manager_network

networks:
  agora_vnf_manager_network:
    driver: bridge
