{{- if .Values.global.image.pullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: harbor-reg
data:
  .dockerconfigjson: {{ .Values.global.image.pullSecret | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}