---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-svc
  #namespace: altice-dhcp
spec:
  selector:
    app: alticelabs-dhcp-relay-db
  ports:
    - name: postgres-db-svc
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
  