apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.env.obbaaVnfInstanceName }}
  ports:
    - name: localport
      protocol: UDP
      port: 67
      targetPort: 67      
      #nodePort: 31052  #external port
    - name: netconfport
      protocol: TCP
      port: 33005
      targetPort: 33005      
      nodePort: {{ .Values.service.netconfApi.externalPort }}
    - name: socketgrpc
      protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: {{ .Values.service.grpc.externalPort }}