name: ci

on:
  push:
    branches:
      - main 

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      # - name: Add bitname helm repository
      #   run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Custom packaging
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
          rm -rf .cf-release-packages
          mkdir -p .cr-release-packages
          helm package charts/dhcp-chart --app-version=$GITHUB_ENV --version=$GITHUB_ENV --destination=.cr-release-packages

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.6.0
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: askcloudarchitect/chart-releaser-action@skip-packaging-option
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
